Restyle header
subvisual/subvisual.com pull request #510
Opened 2023-03-30 19:48 UTC by jreis13

Why:

- Header changes on the design;

These changes address the need by:

- Updating `Header` and its styles;
- Adding home-page and post images;
- Adding `MainHero`;
- Adding `Layouts`;
- Updating `Logo`;
- Updating `NavLinks`;

2023-04-06 12:24 UTC, mirhamasala commented on src/components/Author/index.jsx
> +)
I believe @gabrielpoca converted all the arrow functions

```suggestion
function renderAuthor({ key, name })  {
 return <Link to={`/blog/author/${key}`}>{name}</Link>
}
```

2023-04-06 12:25 UTC, mirhamasala commented on src/components/Author/index.module.scss
> +  }
Let's move out layout properties to a layout component or to the "page component" that's holding the `Author` component

2023-04-06 12:28 UTC, mirhamasala commented on src/components/Author/index.module.scss
> +.picture {
Same

2023-04-06 12:29 UTC, mirhamasala commented on config/node/createPages.js
> +
@gabrielpoca Do we want tag/category pages?

2023-04-06 12:37 UTC, mirhamasala commented on src/components/Header/index.jsx
> +    }
Let's read up on when effects need to be cleaned up.

2023-04-06 12:38 UTC, mirhamasala commented on src/components/Header/index.jsx
> +  const [desktop, setDesktop] = useState(false)
It's good practice to prefix Boolean states with `is` or `has` etc.

2023-04-06 12:38 UTC, mirhamasala commented on src/components/Header/index.jsx
> +    }
Can be a ternary.

2023-04-06 12:43 UTC, mirhamasala commented on src/components/Header/index.jsx
> +  }, [])
Let's look into dependencies arrays for event listeners

2023-04-06 12:46 UTC, mirhamasala commented on src/components/Header/index.jsx
> +    <header className={scroll ? styles.scrolled : styles.root}>
Doesn't `scroll` always return `true`?

2023-04-06 12:52 UTC, mirhamasala commented on src/components/Header/index.module.scss
> +  color: #403f4c;
Let's use vars here

2023-04-06 12:53 UTC, mirhamasala commented on src/components/MainHero/index.module.scss
> +  color: #fff;
🎨

2023-04-06 12:56 UTC, mirhamasala commented on src/components/NavLinks/index.jsx
> +          <NavLink to={PEOPLE_PATH} title="People">
Leftover `title`

2023-04-06 12:56 UTC, mirhamasala commented on src/components/NavLinks/index.module.scss
> +  margin-right: 86px;
🚨

2023-04-06 13:00 UTC, mirhamasala commented on src/components/NavMenu/index.module.scss
> +}
Same .. probably can be a `flex` or `grid` with `gap`

2023-04-06 13:35 UTC, mirhamasala commented on src/components/PostTitle/index.jsx
> +  return <p className={styles.root}>{children}</p>
Should this not be an `h1`?

2023-04-06 13:36 UTC, mirhamasala commented on src/components/PostTitle/index.module.scss
> +  margin-top: 290px;
🚨

2023-04-06 13:36 UTC, mirhamasala commented on src/components/PostTitle/index.module.scss
> +    padding-left: 56px;
🚨

2023-04-06 13:36 UTC, mirhamasala commented on src/components/PostTitle/index.module.scss
> +    padding-left: 118px;
🚨

2023-04-06 13:37 UTC, mirhamasala commented on src/components/Tags/index.jsx
> +      {tags ? (
What happens to this component if there are no `tags`? Should we assume that if we're using this component there are always `tags`?

2023-04-06 13:38 UTC, mirhamasala commented on src/components/Tags/index.module.scss
> +  margin-right: 16px;
Same as before. Look into using a `flex` container or `grid` with `gap`

2023-04-06 13:38 UTC, mirhamasala commented on src/components/Title/index.jsx
> +  return <p className={styles.root}>{children}</p>
`h1`?

2023-04-06 13:39 UTC, mirhamasala commented on src/components/Title/index.module.scss
> +  margin-top: 290px;
🚨

2023-04-06 13:44 UTC, mirhamasala commented on src/pages/tags.js
> +}
CSS: `text-transform: capitalize;`

2023-04-06 13:48 UTC, mirhamasala requested changes
Wow, lots of good work here @jreis13! Just needs a bit of clean up but nothing major. Well done! (Let's just check with @gabrielpoca what to do about those tag pages since I don't believe there's a design/plan for it. Though, a really nice idea!)

2023-04-10 09:34 UTC, gabrielpoca commented
@mirhamasala @jreis13  I squashed my `gp-show-categories` into a single commit. Just merge this branch into that one and then we can merge everything together to master.

2023-04-12 10:53 UTC, mirhamasala commented
@jreis13

2023-04-14 14:45 UTC, merged